server:
  port: 8082
  tomcat:
    threads:
      max: 50 # 允许的最大线程数
    accept-count: 50 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接

# Feign 配置
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
  sentinel:
    enabled: true

# Sentinel 配置
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8090  # Sentinel Dashboard 地址
      http-method-specify: true  # 开启请求方式前缀

      feign:
        enabled: true  # 开启 Feign Sentinel 支持

hm:
  db:
    database: hm-cart
    un: root
    pw: 123456
    swagger:
      tittle: "黑马购物车文档"
      package: com.hmall.cart.controller
